import { FormStep } from "@/types/form";

// NOTE: Replace these placeholder video URLs with your actual video URLs
// You can use URLs from services like Vimeo, YouTube, or your own hosted videos
export const formSteps: FormStep[] = [
  {
    id: "welcome",
    type: "info",
    videoUrl: "/video-1.mp4",
    question: "",
  },
  {
    id: "region",
    type: "multiple-choice",
    videoUrl: "/video-2.mp4",
    question: "Dans quelle région vis-tu ? 🌏",
    fieldName: "region",
    options: [
      { id: "europe", label: "A: Europe" },
      { id: "amerique", label: "B: AMERIQUE DU NORD/SUD" },
      { id: "dom-tom", label: "C: DOM-TOM" },
      { id: "asie", label: "D: Asie" },
      { id: "afrique", label: "E: AFRIQUE" },
      { id: "oceanie", label: "F: Océanie" },
    ],
  },
  {
    id: "contact",
    type: "form",
    videoUrl: "/video-2.mp4",
    question: "Dans quelle région vis-tu ? 🌏",
    fields: [
      {
        name: "name",
        label: "Nom complet",
        type: "text",
        placeholder: "*Ton prénom",
        required: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "*Ton adresse e-mail",
        required: true,
      },
      {
        name: "phone",
        label: "Téléphone",
        type: "tel",
        placeholder: "* Ton numéro Whatsapp",
        required: true,
      },
    ],
  },
  {
    id: "social-media",
    type: "multiple-choice",
    videoUrl: "/video-3.mp4",
    question: "Sur quels réseaux te trouves-tu actuellement?",
    fieldName: "social-media",
    options: [
      { id: "instagram", label: "A: INSTAGRAM" },
      { id: "tik-tok", label: "B: TIKTOK" },
      { id: "les-deux", label: "C: LES DEUX" },
      { id: "aucun", label: "D: AUCUN" },
    ],
  },
  {
    id: "pseudo",
    type: "text-input",
    videoUrl: "/video-4.mp4",
    question: "Quel est ton @pseudo ?",
    placeholder: "Écrivez ici...",
    fieldName: "pseudo",
    inputType: "textarea",
  },
  {
    id: "niche",
    type: "text-input",
    videoUrl: "/video-5.mp4",
    question: "Quel est ton domaine d'activité/Niche ?",
    placeholder: "Écrivez ici...",
    fieldName: "niche",
    inputType: "textarea",
  },
  {
    id: "time",
    type: "multiple-choice",
    videoUrl: "/video-6.mp4",
    question: "Depuis combien de temps ?",
    fieldName: "time",
    options: [
      { id: "moins-de-1-an", label: "A: Moins de 1 an" },
      { id: "plus-de-1-an", label: "B: Plus de 1 an" },
    ],
  },
  {
    id: "problem",
    type: "text-input",
    videoUrl: "/video-7.mp4",
    question: "QExplique ton problème",
    placeholder: "Écrivez ici...",
    fieldName: "problem",
    inputType: "textarea",
  },
  {
    id: "money",
    type: "multiple-choice",
    videoUrl: "/video-8.mp4",
    question: "TON CHIFFRE D'AFFAIRE ?",
    fieldName: "money",
    options: [
      { id: "€0-€5k", label: "A: €0 - €5K" },
      { id: "€5k-€10k", label: "B: €5K - €10K" },
      { id: "€10k-€50k", label: "B: €10K - €50K" },
      { id: "€50k+", label: "B: €50K+" },
    ],
  },
  {
    id: "budget",
    type: "multiple-choice",
    videoUrl: "/video-9.mp4",
    question: "Quel serait ton budget ?",
    fieldName: "budget",
    options: [
      { id: "1000-1500€", label: "A: 1000 - 1500€" },
      { id: "1500-3000€", label: "B: 1500 - 3000€" },
      { id: "plus-de-3000€", label: "B: Plus de 3000€" },
    ],
  },
  {
    id: "appuie-ensuite-sur-ok",
    type: "multiple-choice",
    videoUrl: "/video-10.mp4",
    question: "Appuie ensuite sur ok",
    fieldName: "budget",
    options: [
      { id: "Dès-que-possible", label: "A: Dès que possible" },
      { id: "d’ici-1-à-2-semaines", label: "B: D’ici 1 à 2 semaines" },
      { id: "pas-encore-prêt.e-à-commencer", label: "B: Pas encore prêt.e à commencer" },
    ],
  },
  {
    id: "completion",
    type: "completion",
    videoUrl: "/video-end.mp4",
    title: "Merci d'avoir complété le formulaire!",
    message: "Réservez maintenant votre consultation gratuite",
  },
];
