import { FormStep } from "@/types/form";

// NOTE: Replace these placeholder video URLs with your actual video URLs
// You can use URLs from services like Vimeo, YouTube, or your own hosted videos
export const formSteps: FormStep[] = [
  {
    id: "welcome",
    type: "info",
    videoUrl: "/video-1.mp4",
    question: "",
  },
  {
    id: "region",
    type: "multiple-choice",
    videoUrl: "/video-2.mp4",
    question: "Dans quelle région vis-tu ? 🌏",
    fieldName: "region",
    options: [
      { id: "europe", number: "A", label: "Europe" },
      { id: "amerique", number: "B", label: "AMERIQUE DU NORD/SUD" },
      { id: "dom-tom", number: "C", label: "DOM-TOM" },
      { id: "asie", number: "D", label: "Asie" },
      { id: "afrique", number: "E", label: "AFRIQUE" },
      { id: "oceanie", number: "F", label: "Océanie" },
    ],
  },
  {
    id: "contact",
    type: "form",
    videoUrl: "/video-2.mp4",
    question: "Dans quelle région vis-tu ? 🌏",
    fields: [
      {
        name: "name",
        label: "Nom complet",
        type: "text",
        placeholder: "*Ton prénom",
        required: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "*Ton adresse e-mail",
        required: true,
      },
      {
        name: "phone",
        label: "Téléphone",
        type: "tel",
        placeholder: "* Ton numéro Whatsapp",
        required: true,
      },
    ],
  },
  {
    id: "social-media",
    type: "multiple-choice",
    videoUrl: "/video-3.mp4",
    question: "Sur quels réseaux te trouves-tu actuellement?",
    fieldName: "social-media",
    options: [
      { id: "instagram", number: "A", label: "INSTAGRAM" },
      { id: "tik-tok", number: "B", label: "TIKTOK" },
      { id: "les-deux", number: "C", label: "LES DEUX" },
      { id: "aucun", number: "D", label: "AUCUN" },
    ],
  },
  {
    id: "pseudo",
    type: "text-input",
    videoUrl: "/video-4.mp4",
    question: "Quel est ton @pseudo ?",
    placeholder: "Écrivez ici...",
    fieldName: "pseudo",
    inputType: "textarea",
  },
  {
    id: "niche",
    type: "text-input",
    videoUrl: "/video-5.mp4",
    question: "Quel est ton domaine d'activité/Niche ?",
    placeholder: "Écrivez ici...",
    fieldName: "niche",
    inputType: "textarea",
  },
  {
    id: "time",
    type: "multiple-choice",
    videoUrl: "/video-6.mp4",
    question: "Depuis combien de temps ?",
    fieldName: "time",
    options: [
      { id: "moins-de-1-an", number: "A", label: "Moins de 1 an" },
      { id: "plus-de-1-an", number: "B", label: "Plus de 1 an" },
    ],
  },
  {
    id: "problem",
    type: "text-input",
    videoUrl: "/video-7.mp4",
    question: "QExplique ton problème",
    placeholder: "Écrivez ici...",
    fieldName: "problem",
    inputType: "textarea",
  },
  {
    id: "money",
    type: "multiple-choice",
    videoUrl: "/video-8.mp4",
    question: "TON CHIFFRE D'AFFAIRE ?",
    fieldName: "money",
    options: [
      { id: "€0-€5k", number: "A", label: "€0 - €5K" },
      { id: "€5k-€10k", number: "B", label: "€5K - €10K" },
      { id: "€10k-€50k", number: "C", label: "€10K - €50K" },
      { id: "€50k+", number: "D", label: "€50K+" },
    ],
  },
  {
    id: "budget",
    type: "multiple-choice",
    videoUrl: "/video-9.mp4",
    question: "Quel serait ton budget ?",
    fieldName: "budget",
    options: [
      { id: "1000-1500€", number: "A", label: "1000 - 1500€" },
      { id: "1500-3000€", number: "B", label: "1500 - 3000€" },
      { id: "plus-de-3000€", number: "C", label: "Plus de 3000€" },
    ],
  },
  {
    id: "appuie-ensuite-sur-ok",
    type: "multiple-choice",
    videoUrl: "/video-10.mp4",
    question: "Appuie ensuite sur ok",
    fieldName: "budget",
    options: [
      { id: "Dès-que-possible", number: "A", label: "Dès que possible" },
      { id: "d’ici-1-à-2-semaines", number: "B", label: "D’ici 1 à 2 semaines" },
      { id: "pas-encore-prêt.e-à-commencer", number: "C", label: "Pas encore prêt.e à commencer" },
    ],
  },
  {
    id: "completion",
    type: "completion",
    videoUrl: "/video-end.mp4",
    title: "Merci d'avoir complété le formulaire!",
    message: "Réservez maintenant votre consultation gratuite",
  },
];
